version: '1.0.{build}'

configuration:
- Release

platform: Any CPU

environment:
  # Don't report back to the mothership
 DOTNET_CLI_TELEMETRY_OPTOUT: 1

dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'

init:
- cmd: git config --global core.autocrlf true
- ps: $Env:LABEL = "preview1-" + $Env:APPVEYOR_BUILD_NUMBER.PadLeft(5, "0")

install:
- pip install codecov

before_build:
- appveyor-retry dotnet restore -v Minimal

build_script:
- dotnet build "src\TodoApi.CertAuth\TodoApi.CertAuth.csproj" -c %CONFIGURATION% --no-dependencies --version-suffix %LABEL%
- dotnet build "src\TodoApi\TodoApi.csproj" -c %CONFIGURATION% --no-dependencies --version-suffix %LABEL%
- dotnet build "tests\UTest\TodoApi.Tests.UTests\TodoApi.Tests.UTests.csproj" -c %CONFIGURATION% --no-dependencies --version-suffix %LABEL%

after_build:
- dotnet pack "src\TodoApi.CertAuth\TodoApi.CertAuth.csproj" -c %CONFIGURATION% --no-build --version-suffix %LABEL%
- dotnet pack "src\TodoApi\TodoApi.csproj" -c %CONFIGURATION% --no-build --version-suffix %LABEL%
- dotnet pack "tests\UTest\TodoApi.Tests.UTests\TodoApi.Tests.UTests.csproj" -c %CONFIGURATION% --no-build --version-suffix %LABEL%
- ps: >-
    Add-AppveyorMessage
    "NuGet artifact not deployed. Version. $env:APPVEYOR_BUILD_VERSION"
    -Category "Information" 
    -Details "The NuGet package is not published automatically, but can be published through the AppVeyor Deploy UI.
    APPVEYOR_BUILD_FOLDER: %APPVEYOR_BUILD_FOLDER%
    ENV: $env:APPVEYOR_BUILD_FOLDER"

test_script:
- >-
    OpenCover.Console.exe
    -register:user
    -target:"dotnet.exe"
    -targetargs:"test tests\UTest\TodoApi.Tests.UTests\TodoApi.Tests.UTests.csproj"
    -filter:"+[*]* -[*.Tests]*"
    -output:"%APPVEYOR_BUILD_FOLDER%\coverage.xml"
    -excludebyattribute:*.ExcludeFromCodeCoverage*
    -returntargetcode

after_test:
- codecov -X gcov -f %APPVEYOR_BUILD_FOLDER%\coverage.xml

artifacts:
- path: artifacts\**\*.*
# - path: 'coverage.xml'

# cache:
#  - '%USERPROFILE%\.nuget\packages -> **\*.csproj'
#  - '%LocalAppData%\NuGet\Cache'